import os.path
import os
import glob
import time
import numpy as np
from fpdf import FPDF
import matplotlib as mpl
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from matplotlib.ticker import FormatStrFormatter
import numpy as np
from mpl_toolkits.axes_grid1 import make_axes_locatable


def plotter(X, Y, Z, fname: str, title: str, unit: int, vmin, vmax):

    pc = ccrs.PlateCarree()
    fig = plt.figure(figsize=(16, 8))
    ax = plt.axes(projection=pc)
    ax.set_extent([-180, 180,
                   -90, 90], crs=pc)
    im = ax.imshow(Z, origin='lower',
                   extent=[-180, 180,
                           -90, 90],
                   interpolation='nearest', aspect='auto', vmin=vmin, vmax=vmax,
                   cmap=mpl.colormaps['rainbow'], transform=pc)
    ax.coastlines(resolution='50m', color='black', linewidth=4)
    # fixing tickers
    x_ticks = np.arange(-180,
                        180, 40)
    x_labels = np.linspace(-180, 80, np.size(x_ticks))
    ax.set_xticks(x_ticks)
    ax.set_xticklabels(x_labels, fontsize=18)
    ax.xaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    y_ticks = np.arange(-90, 90, 20)
    y_labels = np.linspace(-90, 90, np.size(y_ticks))
    ax.set_yticks(y_ticks)
    ax.set_yticklabels(y_labels, fontsize=18)
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    # plotting lat and lon
    plt.xlabel('Lon', fontsize=20)
    plt.ylabel('Lat', fontsize=20)
    cbar = plt.colorbar(im)
    cbar.ax.tick_params(labelsize=18)
    if unit == 1:
        cbar.set_label(r'$[ \times 10^{15}molec.cm^{-2}] $', fontsize=18)
    elif unit == 2:
        cbar.set_label('$ [Unitless] $', fontsize=18)
    elif unit == 3:
        cbar.set_label('$ [DU] $', fontsize=18)
    elif unit == 4:
        cbar.set_label(r'$[ \times 10^{18}molec.cm^{-2}] $', fontsize=18)
    elif unit == 5:
        cbar.set_label(r'$[ppmv] $', fontsize=18)
    plt.title(title, loc='left', fontweight='bold', fontsize=20)
    plt.tight_layout()
    fig.savefig(fname, format='png', dpi=300)
    plt.close()


def topdf(fname: str, folder: str, pdf_output: str):
    ''' 
    save all pngs to a pdf report
    '''
    def header(pdfobj, title, fsize=22):
        # Arial bold 15
        pdfobj.set_font('Arial', 'B', fsize)
        # Calculate width of title and position
        w = pdfobj.get_string_width(title) + 6
        pdfobj.set_x((210 - w) / 2)
        pdfobj.set_fill_color(255, 255, 255)
        pdfobj.set_text_color(0, 0, 0)
        # Thickness of frame (1 mm)
        pdfobj.set_line_width(1)
        # Title
        pdfobj.cell(w, 9, title, 1, 1, 'C', 1)
        # Line break
        pdfobj.ln(10)
        return w

    def body(pdfobj, bd1):
        # Times 12
        pdfobj.set_font('Times', '', 12)
        # Output justified text
        pdfobj.multi_cell(0, 5, bd1)
        # Line break
        pdfobj.ln(1)

    # call the fpdf obj
    pdf = FPDF(orientation="landscape")
    pdf.add_page()
    title = 'The Optimal Interpolation Report generated by the OI-SAT-GMI tool'
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(280, 100, txt=title, border=0, ln=1, align="C")
    pdf.cell(280, 20, txt='Amir H. Souri', border=0, ln=1, align="C")
    pdf.cell(280, 20, txt='Contact: ahsouri@gmail.com',
             border=0, ln=1, align="C")
    t = time.localtime()
    current_time = time.strftime("%Y-%m-%d %H:%M:%S", t)
    pdf.cell(280, 20, txt='Created at: ' +
             current_time, border=0, ln=1, align="C")

    # printing grayscales
    map_plots = sorted(glob.glob('temp/*' + fname + '*.png'))
    for fname in map_plots:
        pdf.add_page()
        pdf.image(fname, h=pdf.eph, w=pdf.epw+20)

    # writing
    if not os.path.exists(folder):
        os.makedirs(folder)

    pdf.output(folder + '/' + pdf_output, 'F')


def report(lon: np.ndarray, lat: np.ndarray, ctm_vcd_before: np.ndarray, ctm_vcd_after: np.ndarray,
           sat_vcd: np.ndarray, sat_err: np.ndarray, increment: np.ndarray, averaging_kernel: np.ndarray, error_OI: np.ndarray,
           aux1: np.ndarray, aux2: np.ndarray, fname: str, ffolder: str, gasname: str):
    '''
    '''
    if not os.path.exists('temp'):
        os.makedirs('temp')
    if gasname == 'HCHO':
        vmin_vcd = 0.0
        vmax_vcd = 20.0
        vmax_error = 15.0
        vmin_incre = -5.0
        vmax_incre = 5.0
        unit = 1
        aux = 'AMF'
    if gasname == 'NO2':
        vmin_vcd = 0.0
        vmax_vcd = 10.0
        vmax_error = 5.0
        vmin_incre = -5.0
        vmax_incre = 5.0
        unit = 1
        aux = 'AMF'
    if gasname == 'O3':
        vmin_vcd = 200.0
        vmax_vcd = 500.0
        vmax_error = 30.0
        vmin_incre = -20.0
        vmax_incre = 20.0
        unit = 3  # DU
    if gasname == 'CO':
        vmin_vcd = 0.0
        vmax_vcd = 3.0
        vmax_error = 0.2
        vmin_incre = -2.0
        vmax_incre = 2.0
        unit = 4
        aux = 'xcol'
        # scaling to match 1x10^18
        ctm_vcd_before = ctm_vcd_before*1e-3
        ctm_vcd_after = ctm_vcd_after*1e-3
        sat_vcd = sat_vcd*1e-3
        sat_err = sat_err*1e-3
        increment = increment*1e-3
        error_OI = error_OI*1e-3
        unit_aux = 5
        vmin_aux = 0
        vmax_aux = 0.15
    plotter(lon, lat, ctm_vcd_before, 'temp/ctm_vcd_before_' +
            fname + '.png', 'CTM VCD (prior)', unit, vmin_vcd, vmax_vcd)
    plotter(lon, lat, ctm_vcd_after, 'temp/ctm_vcd_after_' +
            fname + '.png', 'CTM VCD (posterior)', unit, vmin_vcd, vmax_vcd)
    plotter(lon, lat, sat_vcd, 'temp/ctm_vcd_sat_used_' + fname +
            '.png', 'Satellite Observation (Y)', unit, vmin_vcd, vmax_vcd)
    plotter(lon, lat, sat_err, 'temp/ctm_vcd_sat_zerr_' + fname +
            '.png', 'Satellite Error (So)', unit, 0.0, vmax_error)
    plotter(lon, lat, increment, 'temp/increment_' +
            fname + '.png', 'Increment', unit, vmin_incre, vmax_incre)
    plotter(lon, lat, averaging_kernel, 'temp/dak_' +
            fname + '.png', 'Averaging Kernels', 2, 0.0, 1.0)
    plotter(lon, lat, error_OI, 'temp/error_' +
            fname + '.png', 'OI estimate error', unit, 0.0, vmax_error)
    if aux == "AMF":
        plotter(lon, lat, aux1, 'temp/aux1_' +
            fname + '.png', 'new AMF', 2, 0.0, 4)
        plotter(lon, lat, aux2, 'temp/aux2_' +
            fname + '.png', 'old AMF', 2, 0.0, 4)
    if aux == "xcol":
        print('hi')
        plotter(lon, lat, aux1, 'temp/aux1_' +
            fname + '.png', 'XCO (SAT)', unit_aux, vmin_aux, vmax_aux)
        plotter(lon, lat, aux2, 'temp/aux2_' +
            fname + '.png', 'XCO (CTM-Prior)', unit_aux, vmin_aux, vmax_aux)

    topdf(fname, ffolder, 'OI_report_' + fname + '.pdf')
