# set your python executable path
python_bin: '/discover/nobackup/asouri/miniconda3/bin/python3'

# to run the job on debug queue
debug: True

# number of jobs
num_job: 36

# set the name of CTM model (GMI, ECCOH)
ctm_name: 'ECCOH'

# set the path of CTM netcdf files (either relative or absolute)
ctm_dir: '/discover/nobackup/sstrode/Qchem/QUICKCHEM_July/qOHreplay2/eccoh_Nv/'

# the frequency of CTM files (3-hourly, monthly)
ctm_freq: 'monthly'

# should we average CTMs? (reduce memory overhead by a lot)
ctm_avg: False

# error in the model VCD (%)
ctm_error: 10.0

# target gas (NO2, HCHO)
gas: 'CO'

# the sensor name (OMI, TROPOMI)
sensor: 'MOPITT'

# consider scattering weights (or AKs) (memory intensive)
read_AK: True

# total column or tropospheric column (only applicable for NO2)
troposphere_only: False

# set the path of L2 files
sat_dir: '../oisatgmi/download_bucket/mopitt_CO/'

# starting date (YYYY-MM) and ending date (YYYY-MM) (the end point will be considered)
start_date: '2005-01'
end_date:   '2005-12'

# output folder for PDF reports
output_pdf_dir: './report_CO'

# output folder for NC diags
output_nc_dir: './diag_CO'



