# set your python executable path
python_bin: '/discover/nobackup/asouri/miniconda3/bin/python3'

# to run the job on debug queue
debug: False

# number of jobs
num_job: 24

# set the name of CTM model (GMI, ECCOH)
ctm_name: 'ECCOH'

# set the path of CTM netcdf files (either relative or absolute)
ctm_dir: '/discover/nobackup/asouri/MODELS/QUICKCHEM_2022-07-26/geos5/SBase/holding/eccoh_Nv/'

# the frequency of CTM files (3-hourly, monthly)
ctm_freq: 'monthly'

# should we average CTMs? (reduce memory overhead by a lot)
ctm_avg: True

# error in the model VCD (%)
ctm_error: 10.0

# target gas (NO2, HCHO)
gas: 'CH4'

# the sensor name (OMI, TROPOMI)
sensor: 'GOSAT'

# consider scattering weights (or AKs) (memory intensive)
read_AK: True

# total column or tropospheric column (only applicable for NO2)
troposphere_only: False

# set the path of L2 files
sat_dir: '/discover/nobackup/asouri/SHARED/GOSAT_XCH4/CH4_GOS_OCPR/2009'

# starting date (YYYY-MM) and ending date (YYYY-MM) (the end point will be considered)
start_date: '2009-01'
end_date:   '2009-12'

# output folder for PDF reports
output_pdf_dir: './report_gosat'

# output folder for NC diags
output_nc_dir: './diag_gosat'



